### ISSUE TITLE
Add ability to override reference files in strun commands from calib_prep

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwst_reffiles#8]
These inputs would have to be added to the main configuration file, maybe within the sections for each reference file type? 

Something along the lines of this?

```
readnoise:
    imtypes: DD
    ssbsteps: dq, ipc
    ref_bpm: my_badpix_mask.fits
    ref_ipc: my_ipc_kernel.fits
```
